#!/bin/sh

# Parameters
author="Sahithyen Kanaganayagam <mail@sahithyen.com>"
dotfiles_repo="git@github.com:sahithyen/dotfiles.git"
dotfiles_location="$HOME/.dotfiles"

# This script configures my terminal tools.
# Following binaries need to be in PATH:
#  * git
#  * zsh
#  * tmux
#  * nvim
#  * ag

# Print informations about the tool
echo "dotfiles/install ($author)"
echo "repo: $dotfiles_repo"

# Check dependencies
abort="no"

if ! command -v git > /dev/null 2>&1
then
  echo "You need to install git."
  abort="yes"
fi

if ! command -v zsh > /dev/null 2>&1
then
  echo "You need to install zsh."
  abort="yes"
fi

if ! command -v tmux > /dev/null 2>&1
then
  echo "You need to install tmux."
  abort="yes"
fi

if ! command -v nvim > /dev/null 2>&1
then
  echo "You need to install nvim."
  abort="yes"
fi

if ! command -v ag > /dev/null 2>&1
then
  echo "You need to install ag."
  abort="yes"
fi

if [ "$abort" = "yes" ]
then
  echo "Due to missing dependencies the installation is aborted."
  exit 1
fi

# Get .dotfiles if not already existing
if [ ! -d $dotfiles_location ]
then
  git clone "$dotfiles_repo" "$dotfiles_location"
fi

#
# zsh
#

# Install oh-my-zsh
export RUNZSH=no
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Link configuration
[ -f $HOME/.zshrc ] && mv $HOME/.zshrc $HOME/.zshrc.bak
ln -s $dotfiles_location/zsh/.zshrc $HOME/.zshrc

#
# tmux
#

# Link configuration
[ -f $HOME/.tmux.conf ] && mv $HOME/.tmux.conf $HOME/.tmux.conf.bak
ln -s $dotfiles_location/tmux/.tmux.conf $HOME/.tmux.conf

# Install tpm
tpm_path="$HOME/.tmux/plugins/tpm"
tpm_repo="https://github.com/tmux-plugins/tpm"

if [ ! -d "$tpm_path" ]
then
  git clone --depth 1 "$tpm_repo" "$tpm_path"
fi

# Install plugins
tmux new-session -d -s tpm-install
sleep 1
tmux source-file $HOME/.tmux.conf
"$tpm_path/bin/install_plugins"
tmux kill-session -t tpm-install

#
# fzf
#

fzf_path="$HOME/.fzf"
fzf_repo="https://github.com/junegunn/fzf.git"

if [ ! -d "$fzf_path" ]
then
  git clone --depth 1 "$fzf_repo" "$fzf_path"
fi

$HOME/.fzf/install --no-key-bindings --completion --update-rc

#
# nvim
#

# Link configuration
mkdir -p $HOME/.config/nvim

if [ -f $HOME/.config/nvim/init.vim ]
then
  mv $HOME/.config/nvim/init.vim $HOME/.config/nvim/init.vim.bak
fi

ln -s $dotfiles_location/neovim/.config/nvim/init.vim $HOME/.config/nvim/init.vim

# Install vim-plug
vim_plug_path="$HOME/.local/share/nvim/site/autoload/plug.vim"
vim_plug_url="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

if [ ! -f $vim_plug_path ]
then
  curl -fLo $vim_plug_path --create-dirs $vim_plug_url
fi

# Install plugins
nvim -c "PlugInstall" -c "qa!"

#
# vscode
#

ln -s $dotfiles_location/vscode/settings.json $HOME/.config/Code/User/settings.json
