#!/bin/bash
#
# This script installs and configures my terminal tools.

# Parameters
author="Sahithyen Kanaganayagam <mail@sahithyen.com>"
dotfiles_repo="github.com/sahithyen/dotfiles"

# Print informations about the tool
echo "dotfiles/install ($author)"
echo "repo: $dotfiles_repo"

#
# start
#

# Detect OS
if [[ $(uname) == "Darwin" ]]
then
  os="macOS"
else
  echo "OS is not supported"
  exit 1
fi

# Change to base of the repository
base_dir="${0%/*}"
cd $base_dir

#
# Install packages
#

# Following packages are necessary:
#  * GNU Stow
#  * Git
#  * zsh
#  * tmux
#  * Neovim
#  * The Silver Searcher
#  * fzf
if [[ $os == "macOS" ]]
then
  xcode-select --install

  export HOMEBREW_NO_GITHUB_API=1

  if ! hash brew > /dev/null 2>&1
  then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  brew bundle
fi

#
# zsh
#

if [[ $os == "macOS" ]]
then
  # Add brew's zsh to the allowed shells
  zsh_path="/usr/local/bin/zsh"
  shells_path="/etc/shells"

  count=$(sudo grep $zsh_path $shells_path | wc -l)

  if [[ $count -eq 0 ]]
  then
    echo $zsh_path | sudo tee -a $shells_path > /dev/null
  fi
fi

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed '/\s*env zsh/d')"

# Link configuration
if [[ -f $HOME/.zshrc ]]
then
  rm $HOME/.zshrc
fi

stow zsh -t $HOME

#
# tmux
#

# Link configuration
stow tmux -t $HOME

# Install tpm
tpm_path="$HOME/.tmux/plugins/tpm"
tpm_repo="https://github.com/tmux-plugins/tpm"

if [[ ! -e $tpm_path ]]
then
  git clone $tpm_repo $tpm_path
fi

#
# Neovim
#

# Link configuration
stow neovim -t $HOME

# Install vim-plug
vim_plug_path="$HOME/.local/share/nvim/site/autoload/plug.vim"
vim_plug_url="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
if [[ ! -f $vim_plug_path ]]
then
  curl -fLo $vim_plug_path --create-dirs $vim_plug_url
fi

# Install plugins
nvim -c "PlugInstall" -c "qa!"

