#!/bin/bash
#
# This script installs and configures my terminal tools.

# Parameters
author="Sahithyen Kanaganayagam <mail@sahithyen.com>"
dotfiles_repo="github.com/sahithyen/dotfiles"

# Print informations about the tool
echo "dotfiles/install ($author)"
echo "repo: $dotfiles_repo"

# Detect os
if [[ $(uname) == "Darwin" ]]
then
	os="macOS"
else
	echo "OS is not supported"
	exit 1
fi

# Go to the root of the repository
base_dir="${0%/*}"
cd $base_dir

# Following packages are necessary:
#  * GNU Stow
#  * Git
#  * Neovim
if [[ $os == "macOS" ]]
then
	xcode-select --install

	if ! hash brew
	then
		ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	fi

	brew bundle
fi

# Configure neovim

# Link configuration for neovim
stow neovim -t $HOME

# Install vim-plug
vim_plug_path="$HOME/.local/share/nvim/site/autoload/plug.vim"
vim_plug_url="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
if [[ ! -f $vim_plug_path ]]
then
	curl -fLo $vim_plug_path --create-dirs $vim_plug_url
fi
  
# Install plugins
nvim -c "PlugInstall" -c "qa!"

